hosts:
  - domain: dev.lightapi.net
    path: /
    #base: /home/steve/networknt/light-config-test/light-router/test-portal/lightapi/build
    base: /lightapi/build
    transferMinSize: 10245760
    directoryListingEnabled: false
  - domain: devsignin.lightapi.net
    path: /
    #base: /home/steve/networknt/light-config-test/light-router/test-portal/signin/build
    base: /signin/build
    transferMinSize: 10245760
    directoryListingEnabled: false
