# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasemaven_2_0_x
# release version that is used to generate changelog. This need to be changed every time
version: 2.0.32
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# previous tag used to calculate how many commits in between in the git log
prev_tag: 2.0.31
# last number of pull requests retrieved from the GitHub. 100 minimum.
last: 100
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the release process due to some environmental issue before.
skip_checkout: false
# skip change log generation
skip_change_log: false
# skip check in the generated changelog
skip_checkin: false
# You can skip the last release step so that you can double check the merged result.
skip_release: false
# skip upload release note to the github
skip_release_note: false
# skip deploy after the release
skip_deploy: false
# skip upload release assets
skip_upload: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  - branch: master
    repository:
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/json-overlay.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    - git@github.com:networknt/light-graphql-4j.git
    - git@github.com:networknt/light-hybrid-4j.git
    - git@github.com:networknt/light-codegen.git
    - git@github.com:networknt/light-session-4j.git
    - git@github.com:networknt/light-kafka.git
    - git@github.com:networknt/light-spa-4j.git
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-consumer-4j.git
    # - git@github.com:networknt/light-example-4j.git
    # - git@github.com:networknt/light-docker.git
    # - git@github.com:networknt/light-config-server.git
    # - git@github.com:networknt/light-workflow-4j.git
    - git@github.com:networknt/light-spring-boot.git
    - git@github.com:networknt/light-tram-kafka.git
    - git@github.com:networknt/light-aws-lambda.git
    - git@github.com:networknt/light-chaos-monkey.git
    - git@github.com:lightapi/light-portal.git
    - git@github.com:networknt/light-scheduler.git
    - git@github.com:lightapi/hybrid-command.git
    - git@github.com:lightapi/hybrid-query.git
    - git@github.com:lightapi/market-command.git
    - git@github.com:lightapi/market-query.git
    - git@github.com:lightapi/user-query.git
    - git@github.com:lightapi/user-command.git
    - git@github.com:lightapi/ref-query.git
    - git@github.com:lightapi/ref-command.git
    - git@github.com:lightapi/event-exporter.git
    - git@github.com:lightapi/event-importer.git

# generate changelog.md from github issues and check in
# release to maven central
# merge the changelog.md to develop branch
# publish the release to github repository
release:
  - light-4j
  - json-overlay
  - openapi-parser
  - light-rest-4j
  - light-graphql-4j
  - light-hybrid-4j
  - light-codegen
  - light-session-4j
  - light-kafka
  - light-spa-4j
  - light-consumer-4j
  - light-aws-lambda
  - light-router
  - light-proxy
  - light-spring-boot
  - light-tram-kafka
  - light-chaos-monkey
  - light-portal
  - light-scheduler
  - hybrid-command
  - hybrid-query
  - market-command
  - market-query
  - user-command
  - user-query
  - ref-command
  - ref-query
  - event-exporter
  - event-importer
  
deploy:
  - light-codegen:
    - scp codegen-core/target/codegen-core.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
    - scp codegen-fwk/target/codegen-fwk.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
    - scp codegen-web/target/codegen-web.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
    - scp light-graphql-4j/target/light-graphql-4j-generator.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
    - scp light-hybrid-4j/target/light-hybrid-4j-generator.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
    - scp light-rest-4j/target/light-rest-4j-generator.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
# upload additional assets to the GitHub release page
upload:
  - light-codegen:
    - codegen-cli/target/codegen-cli.jar
  - light-proxy:
    - target/light-proxy.jar
  - light-router:
    - target/light-router.jar
