# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasemaven_2_0_x
# release version that is used to generate changelog. This need to be changed every time
version: 2.1.26
# previous tag used to calculate how many commits in between in the git log
prev_tag: 2.1.25
# last number of pull requests retrieved from the GitHub. 100 minimum.
last: 100
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the release process due to some environmental issue before.
skip_checkout: false
# skip change log generation
skip_change_log: false
# skip check in the generated changelog
skip_checkin: false
# You can skip the last release step so that you can double check the merged result.
skip_release: false
# skip upload release note to the github
skip_release_note: false
# skip deploy after the release
skip_deploy: true
# skip upload release assets
skip_upload: true
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  - branch: master
    repository:
      - git@github.com:networknt/light-4j.git
      - git@github.com:networknt/json-overlay.git
      - git@github.com:networknt/openapi-parser.git
      - git@github.com:networknt/light-rest-4j.git
      - git@github.com:networknt/light-graphql-4j.git
      - git@github.com:networknt/light-hybrid-4j.git
      - git@github.com:networknt/light-codegen.git
      - git@github.com:networknt/light-session-4j.git
      - git@github.com:networknt/light-kafka.git
      - git@github.com:networknt/light-spa-4j.git
      - git@github.com:networknt/light-proxy.git
      - git@github.com:networknt/light-router.git
      - git@github.com:networknt/light-gateway.git
      - git@github.com:networknt/http-sidecar.git
      - git@github.com:networknt/light-oauth2.git
      - git@github.com:networknt/oauth-kafka.git
      - git@github.com:networknt/light-tokenization.git
      - git@github.com:networknt/light-consumer-4j.git
    # - git@github.com:networknt/light-config-server.git
      - git@github.com:networknt/light-spring-boot.git
      - git@github.com:networknt/light-aws-lambda.git
      - git@github.com:networknt/light-chaos-monkey.git
      - git@github.com:lightapi/light-portal.git
      - git@github.com:networknt/light-scheduler.git
      - git@github.com:networknt/light-controller.git
      - git@github.com:lightapi/hybrid-command.git
      - git@github.com:lightapi/hybrid-query.git
      - git@github.com:lightapi/market-command.git
      - git@github.com:lightapi/market-query.git
      - git@github.com:lightapi/user-query.git
      - git@github.com:lightapi/user-command.git
      - git@github.com:lightapi/ref-query.git
      - git@github.com:lightapi/ref-command.git
      - git@github.com:lightapi/event-exporter.git
      - git@github.com:lightapi/event-importer.git
      - git@github.com:lightapi/maproot-command.git
      - git@github.com:lightapi/maproot-query.git

# generate changelog.md from github issues and check in
# release to maven central
# merge the changelog.md to develop branch
# publish the release to github repository
release:
  - networknt/light-4j
  - networknt/json-overlay
  - networknt/openapi-parser
  - networknt/light-rest-4j
  - networknt/light-graphql-4j
  - networknt/light-hybrid-4j
  - networknt/light-codegen
  - networknt/light-session-4j
  - networknt/light-kafka
  - networknt/light-spa-4j
  - networknt/light-consumer-4j
  - networknt/light-aws-lambda
  - networknt/light-chaos-monkey
  - networknt/light-router
  - networknt/light-proxy
  - networknt/light-gateway
  - networknt/http-sidecar
  - networknt/light-spring-boot
  - lightapi/light-portal
  - networknt/light-scheduler
  - networknt/light-controller
  - lightapi/hybrid-command
  - lightapi/hybrid-query
  - lightapi/market-command
  - lightapi/market-query
  - lightapi/user-command
  - lightapi/user-query
  - lightapi/ref-command
  - lightapi/ref-query
  - lightapi/event-exporter
  - lightapi/event-importer
  - lightapi/maproot-command
  - lightapi/maproot-query
  - networknt/light-oauth2
  - networknt/oauth-kafka

# deploy:
#   - light-codegen:
#     - scp codegen-core/target/codegen-core.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
#     - scp codegen-fwk/target/codegen-fwk.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
#     - scp codegen-web/target/codegen-web.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
#     - scp light-graphql-4j/target/light-graphql-4j-generator.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
#     - scp light-hybrid-4j/target/light-hybrid-4j-generator.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
#     - scp light-rest-4j/target/light-rest-4j-generator.jar steve@devops:/home/steve/networknt/light-config-test/light-codegen/2_0_x/service
# upload additional assets to the GitHub release page
# upload:
#   - networknt/light-codegen:
#     - codegen-cli/target/codegen-cli.jar
#   - networknt/light-proxy:
#     - target/light-proxy.jar
#   - networknt/light-router:
#     - target/light-router.jar
