# Workspace that is used for this operation. Most of time, this is done on local.
workspace: light-portal_2_0_x
# new upgraded version. This needs to be changed for every release.
version: 2.0.18
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# previous tag used to calculate how many commits in between in the git log
prev_tag: 2.0.17
# last number of pull requests retrieved from the GitHub. 100 minimum.
last: 100
# skip checkout if you know all latest code has been checkout in the previous build
skip_checkout: false
# skip maven build if you know the build has been done already
skip_maven: false
# skip gradle build if you know the build has been done already
skip_gradle: true
# skip generate change log
skip_change_log: true
# skip check in the generated changelog
skip_checkin: true
# skip upload release_note if it is already done.
skip_release_note: true
# skip docker publish if it is done already.
skip_docker: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  # here we checkout master branch to publish the images.
  - branch: master
    repository:
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/maproot.git
# maven build
maven:
  - light-portal
  # - chain-reader
  # - taiji-blockchain
  # - light-codegen
# gradle build
gradle:
  # - light-codegen

# update changelog in master, merge it to develop and publish to github.com
release:
  # - light-codegen

# build docker image and push to docker hub
docker:
  - light-portal/hybrid-command
  - light-portal/hybrid-query
