workspace: lightapi
# indicate if you want to skip checkout. yes if you know that all repositories are just checkout
# or the last time the build was failed and you just want to retry without changing anything.
skip_checkout: false
# Just checkout the repositories for backup or some other tasks
skip_build: false
# If this value is set to true, then only checkout and build will be called. It is
# very useful if you just want to install the develop branch modules into your .m2
# local repo. Also, some of our customers have constraint test environment to run
# unit and integration test only and another environment to run all of tests.
skip_test: false
# skip copy file if necessary.
skip_copyFile: true
# skip copyWildcardFile
skip_copyWildcardFile: false
# skip start
skip_start: true

# Execute this set of tasks in order
# setup is called before any of the tasks
# teardown and stop are called regardless of a succesful/failed light-bot run
tasks:
  # one set of operations
  checkoutSetOne: checkout
  buildSetOne: build
  copyProjectFiles: copyFile
  copyWildcardFile: copyWildcardFile

checkout:
  checkoutSetOne:
    - branch: master
      skip: false
      repository:
        - git@github.com:lightapi/light-portal.git
        - git@github.com:lightapi/hybrid-query.git
        - git@github.com:lightapi/hybrid-command.git
        - git@github.com:lightapi/user-query.git
        - git@github.com:lightapi/user-command.git
        - git@github.com:lightapi/ref-command.git
        - git@github.com:lightapi/ref-query.git
        - git@github.com:lightapi/event-exporter.git
        - git@github.com:lightapi/event-importer.git
        - git@github.com:lightapi/oauth-kafka.git
        - git@github.com:lightapi/light-scheduler.git
        - git@github.com:lightapi/light-controller.git
        - git@github.com:lightapi/light-config-server.git
        - git@github.com:lightapi/maproot-command.git
        - git@github.com:lightapi/maproot-query.git
        - git@github.com:lightapi/portal-config-loc.git
        - git@github.com:lightapi/light-portal-doc.git
        - git@github.com:lightapi/portal-view.git
        - git@github.com:lightapi/client-query.git
        - git@github.com:lightapi/client-command.git
        - git@github.com:lightapi/oauth-command.git
        - git@github.com:lightapi/oauth-query.git
        - git@github.com:lightapi/service-query.git
        - git@github.com:lightapi/service-command.git
        - git@github.com:lightapi/rule-query.git
        - git@github.com:lightapi/rule-command.git
        - git@github.com:lightapi/role-command.git
        - git@github.com:lightapi/role-query.git
        - git@github.com:lightapi/position-query.git
        - git@github.com:lightapi/position-command.git
        - git@github.com:lightapi/attribute-command.git
        - git@github.com:lightapi/attribute-query.git
        - git@github.com:lightapi/group-query.git
        - git@github.com:lightapi/group-command.git
        - git@github.com:lightapi/blog-query.git
        - git@github.com:lightapi/blog-command.git
        - git@github.com:lightapi/category-query.git
        - git@github.com:lightapi/category-command.git
        - git@github.com:lightapi/config-query.git
        - git@github.com:lightapi/config-command.git
        - git@github.com:lightapi/document-query.git
        - git@github.com:lightapi/document-command.git
        - git@github.com:lightapi/error-query.git
        - git@github.com:lightapi/error-command.git
        - git@github.com:lightapi/form-query.git
        - git@github.com:lightapi/form-command.git
        - git@github.com:lightapi/host-command.git
        - git@github.com:lightapi/host-query.git
        - git@github.com:lightapi/news-query.git
        - git@github.com:lightapi/news-command.git
        - git@github.com:lightapi/page-query.git
        - git@github.com:lightapi/page-command.git
        - git@github.com:lightapi/schema-query.git
        - git@github.com:lightapi/schema-command.git
        - git@github.com:lightapi/tag-query.git
        - git@github.com:lightapi/tag-command.git
        - git@github.com:lightapi/template-query.git
        - git@github.com:lightapi/template-command.git
        - git@github.com:lightapi/schedule-query.git
        - git@github.com:lightapi/schedule-command.git



build:
  buildSetOne:
    skip: false
    project:
      - light-portal
      - hybrid-query
      - hybrid-command
      - user-query
      - user-command
      - ref-command
      - ref-query
      - event-exporter
      - event-importer
      - oauth-kafka
      - light-scheduler
      - light-controller
      - light-config-server
      - maproot-command
      - maproot-query
      - client-query
      - client-command
      - oauth-command
      - oauth-query
      - service-query
      - service-command
      - rule-query
      - rule-command
      - role-command
      - role-query
      - position-query
      - position-command
      - attribute-command
      - attribute-query
      - group-query
      - group-command
      - blog-query
      - blog-command
      - category-query
      - category-command
      - config-query
      - config-command
      - document-query
      - document-command
      - error-query
      - error-command
      - form-query
      - form-command
      - host-command
      - host-query
      - news-query
      - news-command
      - page-query
      - page-command
      - schema-query
      - schema-command
      - tag-query
      - tag-command
      - template-query
      - template-command
      - schedule-query
      - schedule-command

# copy individual files by specify exact src and dst relative to home and workspace path.
copyFile:
  # populate hybrid-query services
  # api-certification
  - src: light-portal/api-certification/target/api-certification-1.0.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/api-certification-1.0.0.jar
  # oauth-playground
  - src: light-portal/oauth-playground/target/playground-1.0.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/playground-1.0.0.jar
  # light-portal common-util
  - src: light-portal/common-util/target/common-util-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/common-util-0.1.0.jar
  # host-menu
  - src: light-portal/host-menu/common/target/host-menu-common-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/host-menu-common-0.1.0.jar
  - src: light-portal/host-menu/command/target/host-menu-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/host-menu-command-0.1.0.jar
  - src: light-portal/hybrid-query/target/hybrid-query.jar
    dst: light-config-test/light-portal/hybrid-query/service/hybrid-query.jar
  - src: light-portal/host-menu/query/target/host-menu-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/host-menu-query-0.1.0.jar
  - src: light-portal/host-menu/hybrid-query/target/menu-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/menu-query-0.1.0.jar
  # schema-form
  - src: light-portal/schema-form/common/target/schema-form-common-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/schema-form-common-0.1.0.jar
  - src: light-portal/schema-form/command/target/schema-form-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/schema-form-command-0.1.0.jar
  - src: light-portal/schema-form/query/target/schema-form-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/schema-form-query-0.1.0.jar
  - src: light-portal/schema-form/hybrid-query/target/form-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/form-query-0.1.0.jar
  # user-management
  - src: light-portal/user-management/common/target/user-common-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/user-common-0.1.0.jar
  - src: light-portal/user-management/query/target/user-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/user-query-0.1.0.jar
  - src: light-portal/user-management/hybrid-query/target/user-hybrid-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-query/service/user-hybrid-query-0.1.0.jar
  # light-codegen
  - src: light-codegen/codegen-core/target/codegen-core.jar
    dst: light-config-test/light-portal/hybrid-query/service/coregen-core.jar
  - src: light-codegen/codegen-fwk/target/codegen-fwk.jar
    dst: light-config-test/light-portal/hybrid-query/service/codegen-fwk.jar
  - src: light-codegen/light-graphql-4j/target/light-graphql-4j-generator.jar
    dst: light-config-test/light-portal/hybrid-query/service/light-graphql-4j-generator.jar
  - src: light-codegen/light-rest-4j/target/light-rest-4j-generator.jar
    dst: light-config-test/light-portal/hybrid-query/service/light-rest-4j-generator.jar
  - src: light-codegen/light-hybrid-4j/target/light-hybrid-4j-generator.jar
    dst: light-config-test/light-portal/hybrid-query/service//light-hybrid-4j-generator.jar
  - src: light-codegen/codegen-web/target/codegen-web.jar
    dst: light-config-test/light-portal/hybrid-query/service/codegen-web.jar

  # populate hybrid-command services
  - src: light-portal/hybrid-command/target/hybrid-command.jar
    dst: light-config-test/light-portal/hybrid-command/service/hybrid-command.jar
  # common-util
  - src: light-portal/common-util/target/common-util-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/common-util-0.1.0.jar
  # host-menu
  - src: light-portal/host-menu/common/target/host-menu-common-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/host-menu-common-0.1.0.jar
  - src: light-portal/host-menu/command/target/host-menu-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/host-menu-command-0.1.0.jar
  - src: light-portal/host-menu/hybrid-command/target/menu-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/menu-command-0.1.0.jar
  # schema-form
  - src: light-portal/schema-form/common/target/schema-form-common-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/schema-form-common-0.1.0.jar
  - src: light-portal/schema-form/command/target/schema-form-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/schema-form-command-0.1.0.jar
  - src: light-portal/schema-form/hybrid-command/target/form-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/form-command-0.1.0.jar
  # user-management
  - src: light-portal/user-management/common/target/user-common-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/user-common-0.1.0.jar
  - src: light-portal/user-management/command/target/user-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/user-command-0.1.0.jar
  - src: light-portal/user-management/query/target/user-query-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/user-query-0.1.0.jar
  - src: light-portal/user-management/hybrid-command/target/user-hybrid-command-0.1.0.jar
    dst: light-config-test/light-portal/hybrid-command/service/user-hybrid-command-0.1.0.jar
# copy files with Glob pattern from src folder to dst folder both in home and workspace.
copyWildcardFile:
  # query
  - src: client-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: client-query-*[!javadoc][!sources].jar
  - src: oauth-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: oauth-query-*[!javadoc][!sources].jar
  - src: service-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: service-query-*[!javadoc][!sources].jar
  - src: rule-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: rule-query-*[!javadoc][!sources].jar
  - src: role-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: role-query-*[!javadoc][!sources].jar
  - src: position-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: position-query-*[!javadoc][!sources].jar
  - src: attribute-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: attribute-query-*[!javadoc][!sources].jar
  - src: group-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: group-query-*[!javadoc][!sources].jar
  - src: user-query/target
    dst: portal-config-loc/all-in-one/hybrid-query/service
    pattern: user-query-*[!javadoc][!sources].jar

  # command
  - src: client-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: client-command-*[!javadoc][!sources].jar
  - src: oauth-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: oauth-command-*[!javadoc][!sources].jar
  - src: service-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: service-command-*[!javadoc][!sources].jar
  - src: rule-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: rule-command-*[!javadoc][!sources].jar
  - src: role-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: role-command-*[!javadoc][!sources].jar
  - src: position-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: position-command-*[!javadoc][!sources].jar
  - src: attribute-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: attribute-command-*[!javadoc][!sources].jar
  - src: group-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: group-command-*[!javadoc][!sources].jar
  - src: user-command/target
    dst: portal-config-loc/all-in-one/hybrid-command/service
    pattern: user-command-*[!javadoc][!sources].jar


# light-codegen
# The jar file has version number and we are using glob patter to locate the jar files.
# - src: light-codegen//codegen-core/target
#   dst: light-config-test/light-portal/hybrid-query/service
#   pattern: codegen-core-*[!javadoc][!sources].jar
# - src: light-codegen/codegen-fwk/target
#   dst: light-config-test/light-portal/hybrid-query/service
#   pattern: codegen-fwk-*[!javadoc][!sources].jar
# - src: light-codegen/light-graphql-4j/target
#   dst: light-config-test/light-portal/hybrid-query/service
#   pattern: light-graphql-4j-generator-*[!javadoc][!sources].jar
# - src: light-codegen/light-rest-4j/target
#   dst: light-config-test/light-portal/hybrid-query/service
#   pattern: light-rest-4j-generator-*[!javadoc][!sources].jar
# - src: light-codegen/light-hybrid-4j/target
#   dst: light-config-test/light-portal/hybrid-query/service
#   pattern: light-hybrid-4j-generator-*[!javadoc][!sources].jar
# - src: light-codegen/codegen-web/target
#   dst: light-config-test/light-portal/hybrid-query/service
#   pattern: codegen-web-*[!javadoc][!sources].jar
