# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasesnapshot_1_6_x
# release version that is used to generate changelog. This need to be changed every time
version: 1.6.48-SNAPSHOT
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# previous tag used to calculate how many commits in between in the git log
prev_tag: 1.6.47
# last number of pull requests retrieved from the GitHub. 100 minimum.
last: 100
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the release process due to some environmental issue before.
skip_checkout: false
# skip change log generation
skip_change_log: true
# skip check in the generated changelog
skip_checkin: true
# You can skip the last release step so that you can double check the merged result.
skip_release: false
# skip upload release note to the github
skip_release_note: true
# skip deploy after the release
skip_deploy: true
# skip upload release assets
skip_upload: true
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  - branch: 1.6.x
    repository:
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/json-overlay.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    - git@github.com:networknt/light-graphql-4j.git
    - git@github.com:networknt/light-hybrid-4j.git
    - git@github.com:networknt/light-codegen.git
    # - git@github.com:networknt/light-session-4j.git
    - git@github.com:networknt/light-spa-4j.git
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-consumer-4j.git
    - git@github.com:networknt/light-example-4j.git
    - git@github.com:networknt/light-docker.git
    # - git@github.com:networknt/light-config-server.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/light-workflow-4j.git
    - git@github.com:networknt/light-spring-boot.git
    - git@github.com:networknt/light-kafka.git
    - git@github.com:networknt/light-eventuate-4j.git
    - git@github.com:networknt/light-tram-kafka.git
    - git@github.com:networknt/light-tram-4j.git

# generate changelog.md from github issues and check in
# release to maven central
# merge the changelog.md to develop branch
# publish the release to github repository
release:
  - networknt/light-4j
  - networknt/json-overlay
  - networknt/openapi-parser
  - networknt/light-rest-4j
  - networknt/light-graphql-4j
  - networknt/light-hybrid-4j
  - networknt/light-codegen
  # - light-session-4j
  - networknt/light-spa-4j
  - networknt/light-consumer-4j
  - networknt/light-router
  - networknt/light-proxy
  - networknt/light-spring-boot
  - networknt/light-kafka
  - networknt/light-eventuate-4j
  - networknt/light-tram-kafka
  - networknt/light-tram-4j
