# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasedocker_1_5_x
# new upgraded version. This needs to be changed for every release.
version: 1.5.34
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# previous tag used to calculate how many commits in between in the git log
prev_tag: 1.5.33
# last number of pull requests retrieved from the GitHub. 100 minimum.
last: 100
# skip checkout if you know all latest code has been checkout in the previous build
skip_checkout: true
# skip maven build if you know the build has been done already
skip_maven: true
# skip generate change log
skip_change_log: true
# skip check in the generated changelog
skip_checkin: true
# skip upload release_note if it is already done.
skip_release_note: true
# skip docker publish if it is done already.
skip_docker: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  # here we checkout master branch to publish the images.
  - branch: 1.5.x
    repository:
    # - git@github.com:networknt/light-tokenization.git
    # - git@github.com:networknt/light-portal.git
    # - git@github.com:networknt/light-example-4j.git
    # - git@198.55.49.186:lightapi/tokenization.git
    # - git@github.com:networknt/light-codegen.git
    # - git@github.com:networknt/light-docker.git
# maven build
maven:
  # - light-tokenization
  # - light-portal
  # - light-example-4j/discovery/api_a/kubernetes
  # - light-example-4j/discovery/api_b/kubernetes
  # - light-example-4j/discovery/api_c/kubernetes
  # - light-example-4j/discovery/api_d/kubernetes
  # - tokenization
  # - light-codegen

# update changelog in master, merge it to develop and publish to github.com
release:
  # - light-tokenization
  # - light-portal
  # - tokenization
  # - light-codegen

# build docker image and push to docker hub
docker:
  # - light-tokenization
  # - light-portal/hybrid-command
  # - light-portal/hybrid-query
  # - light-example-4j/discovery/api_a/kubernetes
  # - light-example-4j/discovery/api_b/kubernetes
  # - light-example-4j/discovery/api_c/kubernetes
  # - light-example-4j/discovery/api_d/kubernetes
  # - tokenization
  # - light-docker/light-codegen
