  version: '2'
  services:
    # mysql 8.0.x has connection issue so we have used the latest 5.7 version
    # uft8 is supported so that we can use Chinese and Japanese in database tables.
    # to start this docker container, you need to create the mysql folder under user steve
    mysqldb:
      image: mysql:5.7.29
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      ports:
        - 3306:3306
      volumes:
        - ./light-oauth2/mysql:/docker-entrypoint-initdb.d
        - /home/steve/mysql:/var/lib/mysql
      network_mode: host
      environment:
        LANG: C.UTF-8
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_USER: mysqluser
        MYSQL_PASSWORD: mysqlpw
    oauth2-code:
      image: networknt/oauth2-code:2.0.13
      ports:
        - "6881:6881"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-code:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-code"
      #    env: "dev"
    oauth2-token:
      image: networknt/oauth2-token:2.0.13
      ports:
        - "6882:6882"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-token:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    oauth2-service:
      image: networknt/oauth2-service:2.0.13
      ports:
        - "6883:6883"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-service:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    oauth2-client:
      image: networknt/oauth2-client:2.0.13
      ports:
        - "6884:6884"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-client:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-client"
      #    env: "dev"
    oauth2-user:
      image: networknt/oauth2-user:2.0.13
      ports:
        - "6885:6885"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-user:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-user"
      #    env: "dev"
    oauth2-key:
      image: networknt/oauth2-key:2.0.13
      ports:
        - "6886:6886"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-key:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-key"
      #    env: "dev"
    oauth2-refresh-token:
      image: networknt/oauth2-refresh-token:2.0.13
      ports:
        - "6887:6887"
      volumes:
        - ./light-oauth2/mysql/config/oauth2-refresh-token:/config
      environment:
        - STATUS_HOST_IP=38.113.162.51
      network_mode: host
      depends_on:
        - mysqldb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-refresh-token"
      #    env: "dev"
    light-router:
      image:  networknt/light-router:latest
      ports:
        - 8443:8443
      volumes:
        - ./light-router:/config
      network_mode: host
