# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasedocker_2_0_x
# new upgraded version. This needs to be changed for every release.
version: 2.0.32
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# previous tag used to calculate how many commits in between in the git log
prev_tag: 2.0.31
# last number of pull requests retrieved from the GitHub. 100 minimum.
last: 100
# skip checkout if you know all latest code has been checkout in the previous build
skip_checkout: false
# skip maven build if you know the build has been done already
skip_maven: false
# skip gradle build if you know the build has been done already
skip_gradle: true
# skip generate change log
skip_change_log: false
# skip check in the generated changelog
skip_checkin: false
# skip upload release_note if it is already done.
skip_release_note: false
# skip docker publish if it is done already.
skip_docker: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  # here we checkout master branch to publish the images. 
  - branch: master
    repository:
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/oauth-kafka.git
    - git@github.com:networknt/light-tokenization.git
    - git@github.com:networknt/light-reference.git
    - git@github.com:lightapi/hybrid-command.git
    - git@github.com:lightapi/hybrid-query.git
    - git@github.com:networknt/light-example-4j.git
    # - git@github.com:networknt/light-codegen.git
    # - git@github.com:networknt/light-docker.git
    - git@github.com:networknt/kafka-sidecar.git
    - git@github.com:networknt/http-sidecar.git
    - git@github.com:networknt/light-scheduler.git
# maven build
maven:
  - light-proxy
  - light-router
  - light-oauth2
  - light-portal
  - oauth-kafka
  - light-tokenization
  - light-reference

  - light-example-4j/discovery/api_a/kubernetes
  - light-example-4j/discovery/api_b/kubernetes
  - light-example-4j/discovery/api_c/kubernetes
  - light-example-4j/discovery/api_d/kubernetes
  # - light-codegen
  # - kafka-sidecar
  # - http-sidecar
  # - light-scheduler

# update changelog in master, merge it to develop and publish to github.com
release:
  - light-proxy
  - light-router
  - light-oauth2
  - oauth-kafka
  - light-tokenization
  - light-reference
  # - http-sidecar
  # - kafka-sidecar
  # - light-scheduler
  # - light-portal
  # - light-codegen

# build docker image and push to docker hub
docker:
  - light-proxy
  - light-router
  # - light-oauth2/authorize
  - light-oauth2/client
  - light-oauth2/code
  - light-oauth2/key
  - light-oauth2/refresh-token
  - light-oauth2/service
  - light-oauth2/token
  - light-oauth2/user
  - light-oauth2/provider
  - oauth-kafka/oauth-code
  - oauth-kafka/oauth-token
  - oauth-kafka/oauth-key
  - light-tokenization
  - light-reference
  - hybrid-command
  - hybrid-query
  # - light-portal/codegen-server
  - light-example-4j/discovery/api_a/kubernetes
  - light-example-4j/discovery/api_b/kubernetes
  - light-example-4j/discovery/api_c/kubernetes
  - light-example-4j/discovery/api_d/kubernetes
  # - light-docker/light-codegen
  - kafka-sidecar
  - http-sidecar
  - light-scheduler
