# This task is used to delete patch branch from master.
# Workspace that is used for this operation. Most of time, this is done on local.
workspace: deletebranch_patch
# The new branch name that is going to be created
branch: patch
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the create branch process due to some environmental issue before.
skip_checkout: false
# You can skip the delete branch locally if you don't want to remove the local patch branch.
skip_local: false
# You can skip the delete branch remotely if you don't want to remove the remote branch on GitHub.
skip_remote: false
# clone and switch to the branch specified in checkout step.
checkout:
  - branch: master
    repository:
      - git@github.com:networknt/light-4j.git
      - git@github.com:networknt/json-overlay.git
      - git@github.com:networknt/openapi-parser.git
      - git@github.com:networknt/light-rest-4j.git
      - git@github.com:networknt/light-graphql-4j.git
      - git@github.com:networknt/light-hybrid-4j.git
      - git@github.com:networknt/light-codegen.git
      - git@github.com:networknt/light-kafka.git
      - git@github.com:networknt/light-spa-4j.git
      - git@github.com:networknt/light-chaos-monkey.git
      - git@github.com:networknt/light-gateway.git
      - git@github.com:networknt/http-sidecar.git
      - git@github.com:lightapi/oauth-kafka.git
      - git@github.com:networknt/light-tokenization.git
      - git@github.com:lightapi/light-config-server.git
      - git@github.com:networknt/light-spring-boot.git
      - git@github.com:networknt/light-aws-lambda.git
      - git@github.com:networknt/light-lambda-native.git
      - git@github.com:lightapi/light-portal.git
      - git@github.com:lightapi/light-scheduler.git
      - git@github.com:lightapi/light-controller.git
      - git@github.com:lightapi/hybrid-command.git
      - git@github.com:lightapi/hybrid-query.git
      - git@github.com:lightapi/user-query.git
      - git@github.com:lightapi/user-command.git
      - git@github.com:lightapi/oauth-query.git
      - git@github.com:lightapi/oauth-command.git
      - git@github.com:lightapi/rule-query.git
      - git@github.com:lightapi/rule-command.git
      - git@github.com:lightapi/role-query.git
      - git@github.com:lightapi/role-command.git
      - git@github.com:lightapi/group-query.git
      - git@github.com:lightapi/group-command.git
      - git@github.com:lightapi/position-query.git
      - git@github.com:lightapi/position-command.git
      - git@github.com:lightapi/attribute-query.git
      - git@github.com:lightapi/attribute-command.git
      - git@github.com:lightapi/client-query.git
      - git@github.com:lightapi/client-command.git
      - git@github.com:lightapi/service-query.git
      - git@github.com:lightapi/service-command.git
      - git@github.com:lightapi/host-query.git
      - git@github.com:lightapi/host-command.git
      - git@github.com:lightapi/product-query.git
      - git@github.com:lightapi/product-command.git
      - git@github.com:lightapi/deployment-query.git
      - git@github.com:lightapi/deployment-command.git
      - git@github.com:lightapi/instance-query.git
      - git@github.com:lightapi/instance-command.git
      - git@github.com:lightapi/config-query.git
      - git@github.com:lightapi/config-command.git
      - git@github.com:lightapi/ref-query.git
      - git@github.com:lightapi/ref-command.git
      - git@github.com:lightapi/event-exporter.git
      - git@github.com:lightapi/event-importer.git
      - git@github.com:lightapi/maproot-command.git
      - git@github.com:lightapi/maproot-query.git
      - git@github.com:networknt/light-session-4j.git
      - git@github.com:networknt/kafka-sidecar.git
      - git@github.com:networknt/openapi-petstore.git
      - git@github.com:networknt/openapi-market.git
      - git@github.com:networknt/graphql-petstore.git
      - git@github.com:lightapi/error-query.git
      - git@github.com:lightapi/error-command.git
      - git@github.com:lightapi/document-query.git
      - git@github.com:lightapi/document-command.git
      - git@github.com:lightapi/form-query.git
      - git@github.com:lightapi/form-command.git
      - git@github.com:lightapi/blog-query.git
      - git@github.com:lightapi/blog-command.git
      - git@github.com:lightapi/category-query.git
      - git@github.com:lightapi/category-command.git
      - git@github.com:lightapi/schema-query.git
      - git@github.com:lightapi/schema-command.git
      - git@github.com:lightapi/page-query.git
      - git@github.com:lightapi/page-command.git
      - git@github.com:lightapi/news-query.git
      - git@github.com:lightapi/news-command.git
      - git@github.com:lightapi/tag-query.git
      - git@github.com:lightapi/template-query.git
      - git@github.com:lightapi/template-command.git
