# networknt is the working directory under user home. Change this to your working directory
workspace: lightapi
# indicate if you want to skip checkout. yes if you know that all repositories are just checkout
# or the last time the build was failed and you just want to retry without changing anything.
skip_checkout: false
# Just checkout the repositories for backup or some other tasks
skip_build: true
# If this value is set to true, then only checkout and build will be called. It is
# very useful if you just want to install the develop branch modules into your .m2
# local repo. Also, some of our customers have constraint test environment to run
# unit and integration test only and another environment to run all of tests.
skip_test: true
# skip copy file if necessary.
skip_copyFile: true
# skip copyWildcardFile
skip_copyWildcardFile: true
# skip start
skip_start: true

# Execute this set of tasks in order
# setup is called before any of the tasks
# teardown and stop are called regardless of a succesful/failed light-bot run
tasks:
  # one set of operations
  checkoutSetOne: checkout

checkout:
  checkoutSetOne:
    - branch: master
      skip: false
      repository:
        - git@github.com:lightapi/light-portal.git
        - git@github.com:lightapi/hybrid-command.git
        - git@github.com:lightapi/hybrid-query.git
        - git@github.com:lightapi/user-query.git
        - git@github.com:lightapi/user-command.git
        - git@github.com:lightapi/oauth-query.git
        - git@github.com:lightapi/oauth-command.git
        - git@github.com:lightapi/rule-query.git
        - git@github.com:lightapi/rule-command.git
        - git@github.com:lightapi/role-query.git
        - git@github.com:lightapi/role-command.git
        - git@github.com:lightapi/group-query.git
        - git@github.com:lightapi/group-command.git
        - git@github.com:lightapi/position-query.git
        - git@github.com:lightapi/position-command.git
        - git@github.com:lightapi/attribute-query.git
        - git@github.com:lightapi/attribute-command.git
        - git@github.com:lightapi/client-query.git
        - git@github.com:lightapi/client-command.git
        - git@github.com:lightapi/service-query.git
        - git@github.com:lightapi/service-command.git
        - git@github.com:lightapi/host-query.git
        - git@github.com:lightapi/host-command.git
        - git@github.com:lightapi/product-query.git
        - git@github.com:lightapi/product-command.git
        - git@github.com:lightapi/deployment-query.git
        - git@github.com:lightapi/deployment-command.git
        - git@github.com:lightapi/instance-query.git
        - git@github.com:lightapi/instance-command.git
        - git@github.com:lightapi/config-query.git
        - git@github.com:lightapi/config-command.git
        - git@github.com:lightapi/ref-query.git
        - git@github.com:lightapi/ref-command.git
        - git@github.com:lightapi/event-exporter.git
        - git@github.com:lightapi/event-importer.git
        - git@github.com:lightapi/maproot-command.git
        - git@github.com:lightapi/maproot-query.git
        - git@github.com:lightapi/portal-config-loc.git
        - git@github.com:lightapi/light-portal-doc.git
        - git@github.com:lightapi/portal-view.git
        - git@github.com:lightapi/light-scheduler.git
        - git@github.com:lightapi/light-controller.git  
        - git@github.com:lightapi/oauth-kafka.git
        - git@github.com:lightapi/light-config-server.git
        - git@github.com:lightapi/error-query.git
        - git@github.com:lightapi/error-command.git
        - git@github.com:lightapi/document-query.git
        - git@github.com:lightapi/document-command.git
        - git@github.com:lightapi/form-query.git
        - git@github.com:lightapi/form-command.git
        - git@github.com:lightapi/blog-query.git
        - git@github.com:lightapi/blog-command.git
        - git@github.com:lightapi/category-query.git
        - git@github.com:lightapi/category-command.git
        - git@github.com:lightapi/schema-query.git
        - git@github.com:lightapi/schema-command.git
        - git@github.com:lightapi/page-query.git
        - git@github.com:lightapi/page-command.git
        - git@github.com:lightapi/news-query.git
        - git@github.com:lightapi/news-command.git
        - git@github.com:lightapi/tag-query.git
        - git@github.com:lightapi/tag-command.git
        - git@github.com:lightapi/template-query.git
        - git@github.com:lightapi/template-command.git
        - git@github.com:lightapi/schedule-query.git
        - git@github.com:lightapi/schedule-command.git
